echo "Refreshing tables..."
psql -d ai1221_db -f /home/ai1221/main/create_db.sql

echo "Loading all data..."

echo "Loading filmdirector.csv"
cat ./filmdirector.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.filmdirector FROM STDIN CSV HEADER"
echo "Loading has_director_Film.csv"
cat ./has_director_Film.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.has_director_Film FROM STDIN CSV HEADER"
echo "Loading FilmScreenWriter.csv"
cat ./FilmScreenWriter.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.filmscreenwriter FROM STDIN CSV HEADER"
echo "Loading /has_screenwriter.csv"
cat ./has_screenwriter.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.has_screenwriter FROM STDIN CSV HEADER"
echo "Loading FilmActor.csv"
cat ./FilmActor.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.filmactor FROM STDIN CSV HEADER"
echo "Loading has_actor.csv"
cat ./has_actor.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.has_actor FROM STDIN CSV HEADER"
echo "Loading Location.csv"
cat ./Location.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.location FROM STDIN CSV HEADER"
echo "Loading location_museum.csv"
cat ./location_museum.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.location FROM STDIN CSV HEADER"
echo "Loading located_at_Museum.csv"
cat ./located_at_Museum.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.located_at_Museum FROM STDIN CSV HEADER"
echo "Loading has_object_MuseumObject.csv"
cat ./has_object_MuseumObject.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.has_object_MuseumObject FROM STDIN CSV HEADER"
echo "Loading MuseumObjectCreator.csv"
cat ./MuseumObjectCreator.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.MuseumObjectCreator FROM STDIN CSV HEADER"
echo "Loading created_by.csv"
cat ./created_by.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.created_by FROM STDIN CSV HEADER"
echo "Loading MuseumEvent.csv"
cat ./MuseumEvent.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.MuseumEvent FROM STDIN CSV HEADER"
echo "Loading has_event.csv"
cat ./has_event.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.has_event FROM STDIN CSV HEADER"
echo "Loading has_location_FilmTheater.csv"
cat ./has_location_FilmTheater.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.has_location_FilmTheater FROM STDIN CSV HEADER"
echo "/Loading FilmScreening.csv"
cat ./FilmScreening.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.FilmScreening  FROM STDIN CSV HEADER"
echo "/Loading showing_at.csv"
cat ./showing_at.csv | psql -U ai1221 -d ai1221_db -c "COPY culture.showing_at  FROM STDIN CSV HEADER"
